In [21]:
import numpy as np

In [11]:
import pandas as pd

# Replace with the actual path to your file
df = pd.read_csv("C:/Users/ibrah/OneDrive/Masaüstü/all_companies_balance_statements.csv")

In [12]:
# Replace with the actual path to your file
df2 = pd.read_csv("C:/Users/ibrah/OneDrive/Masaüstü/all_companies_cashflow_statements.csv")

In [13]:
# Replace with the actual path to your file
df3 = pd.read_csv("C:/Users/ibrah/OneDrive/Masaüstü/all_companies_income_statements.csv")

In [14]:
# Replace with the actual path to your file
df4 = pd.read_excel("C:/Users/ibrah/OneDrive/Masaüstü/Nimbus-Fintegral Strateji/listof90year.xlsx")

In [15]:
# First, rename columns in each DataFrame to avoid collisions (except the join keys)
df_bs = df.add_prefix('bs_')
df_cf = df2.add_prefix('cf_')
df_is = df3.add_prefix('is_')

# But restore the join keys to their original names
for col in ['symbol', 'calendarYear', 'period']:
    df_bs[col] = df[col]
    df_cf[col] = df2[col]
    df_is[col] = df3[col]

# Now merge them one by one on 'symbol', 'calendarYear', and 'period'
combined_df = df_bs.merge(df_cf, on=['symbol', 'calendarYear', 'period'], how='outer')
combined_df = combined_df.merge(df_is, on=['symbol', 'calendarYear', 'period'], how='outer')

In [16]:
combined_df

,bs_Symbol,bs_Unnamed: 1,bs_date,bs_symbol,bs_reportedCurrency,bs_cik,bs_fillingDate,bs_acceptedDate,bs_calendarYear,bs_period,...,is_incomeBeforeTaxRatio,is_incomeTaxExpense,is_netIncome,is_netIncomeRatio,is_eps,is_epsdiluted,is_weightedAverageShsOut,is_weightedAverageShsOutDil,is_link,is_finalLink
0,AAPL,0.0,2024-09-28,AAPL,USD,320193.0,2024-11-01,2024-11-01 06:01:36,2024.0,FY,...,0.315790,2.974900e+10,9.373600e+10,0.239713,6.110000,6.080000,1.534378e+10,1.540810e+10,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
1,AAPL,1.0,2023-09-30,AAPL,USD,320193.0,2023-11-03,2023-11-02 18:08:27,2023.0,FY,...,0.296740,1.674100e+10,9.699500e+10,0.253062,6.160000,6.130000,1.574423e+10,1.581255e+10,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2,AAPL,2.0,2022-09-24,AAPL,USD,320193.0,2022-10-28,2022-10-27 18:01:14,2022.0,FY,...,0.302040,1.930000e+10,9.980300e+10,0.253096,6.150000,6.110000,1.621596e+10,1.632582e+10,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
3,AAPL,3.0,2021-09-25,AAPL,USD,320193.0,2021-10-29,2021-10-28 18:04:28,2021.0,FY,...,0.298529,1.452700e+10,9.468000e+10,0.258818,5.670000,5.610000,1.670127e+10,1.686492e+10,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
4,AAPL,4.0,2020-09-26,AAPL,USD,320193.0,2020-10-30,2020-10-29 18:06:25,2020.0,FY,...,0.244398,9.680000e+09,5.741100e+10,0.209136,3.310000,3.280000,1.735212e+10,1.752821e+10,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.702985,2.100000e+04,-7.584300e+07,-1.703457,-13.110000,-13.110000,5.787000e+06,5.787000e+06,https://www.sec.gov/Archives/edgar/data/181949...,https://www.sec.gov/Archives/edgar/data/181949...
153346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000e+00,-2.387000e+03,0.000000,-0.000800,-0.000800,3.120097e+06,3.120096e+06,NaN,NaN
153347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,4.240098e+07,-1.146326e+07,-0.370527,-4.040000,-4.040000,2.837772e+06,2.837772e+06,NaN,NaN
153348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.012838,9.480597e+04,1.578190e+05,0.004848,0.010254,0.010254,1.540374e+07,1.540374e+07,NaN,NaN
153349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.012838,9.480597e+04,1.578190e+05,0.004848,0.010254,0.010254,1.540374e+07,1.540374e+07,NaN,NaN

In [ ]:
file_path="C:/Users/ibrah/OneDrive/Masaüstü/newformat.xlsx"

combined_df.to_excel(file_path, index=False)

In [18]:
# Gross Profit / Total Assets
combined_df['gross_profit'] = combined_df['is_revenue'] - combined_df['is_costOfRevenue']
combined_df['gross_ROA'] = combined_df['gross_profit'] / combined_df['bs_totalCurrentAssets']

# EBIT / Market Price (using total stockholders equity as market price proxy)
combined_df['EBIT_to_MP'] = combined_df['is_ebitda'] / combined_df['bs_totalStockholdersEquity']

In [22]:
combined_df['gross_ROA'] = combined_df['gross_ROA'].replace([np.inf, -np.inf], np.nan)
combined_df['EBIT_to_MP'] = combined_df['EBIT_to_MP'].replace([np.inf, -np.inf], np.nan)

In [23]:
# Prepare a list to collect results for each year
ranked_results = []

# Loop over each row in df4 (each year)
for idx, row in df4.iterrows():
    year = row['year']
    prev_year = year - 1

    # Get the tickers for this year, drop NaNs and flatten
    tickers = row[1:].dropna().unique().tolist()

    # Filter combined_df for previous year's financials and relevant tickers
    df_year = combined_df[
        (combined_df['calendarYear'] == prev_year) &
        (combined_df['symbol'].isin(tickers))
    ].copy()

    # Only proceed if there's data
    if df_year.empty:
        continue

    # Rank by gross_ROA (higher is better)
    df_year['rank_gross_ROA'] = df_year['gross_ROA'].rank(ascending=False, method='min')

    # Rank by EBIT_to_MP (higher is better)
    df_year['rank_EBIT_to_MP'] = df_year['EBIT_to_MP'].rank(ascending=False, method='min')

    # Sum ranks
    df_year['combined_score'] = df_year['rank_gross_ROA'] + df_year['rank_EBIT_to_MP']

    # Final ranking based on combined score (lower is better)
    df_year['final_rank'] = df_year['combined_score'].rank(method='min')

    # Add current year for context
    df_year['ranking_year'] = year

    # Save result
    ranked_results.append(df_year)

# Concatenate all results into a single DataFrame
ranked_df = pd.concat(ranked_results, ignore_index=True)

# Optional: sort by year and final rank
ranked_df = ranked_df.sort_values(by=['ranking_year', 'final_rank'])

In [24]:
ranked_df

,bs_Symbol,bs_Unnamed: 1,bs_date,bs_symbol,bs_reportedCurrency,bs_cik,bs_fillingDate,bs_acceptedDate,bs_calendarYear,bs_period,...,is_link,is_finalLink,gross_profit,gross_ROA,EBIT_to_MP,rank_gross_ROA,rank_EBIT_to_MP,combined_score,final_rank,ranking_year
137,GIS,25.0,1999-05-30,GIS,USD,40704.0,1999-08-23,1999-08-23 00:00:00,1999.0,FY,...,https://www.sec.gov/Archives/edgar/data/40704/...,https://www.sec.gov/Archives/edgar/data/40704/...,3.846800e+09,3.489161,7.380633,15.0,3.0,18.0,1.0,2000
196,CPB,25.0,1999-08-01,CPB,USD,16732.0,1999-10-12,1999-10-12 00:00:00,1999.0,FY,...,https://www.sec.gov/Archives/edgar/data/16732/...,https://www.sec.gov/Archives/edgar/data/16732/...,3.571000e+09,2.759660,6.668085,25.0,5.0,30.0,2.0,2000
147,K,24.0,1999-12-31,K,USD,55067.0,2000-03-24,2000-03-24 00:00:00,1999.0,FY,...,https://www.sec.gov/Archives/edgar/data/55067/...,https://www.sec.gov/Archives/edgar/data/55067/...,3.947100e+09,2.515358,1.674127,33.0,9.0,42.0,3.0,2000
125,EXC,25.0,1999-12-31,EXC,USD,1109357.0,1999-12-31,1999-12-30 19:00:00,1999.0,FY,...,NaN,NaN,3.291600e+09,2.714498,0.927611,27.0,16.0,43.0,4.0,2000
27,PEP,25.0,1999-12-25,PEP,USD,77476.0,2000-03-21,2000-03-21 00:00:00,1999.0,FY,...,https://www.sec.gov/Archives/edgar/data/77476/...,https://www.sec.gov/Archives/edgar/data/77476/...,1.301800e+10,3.119578,0.684784,20.0,31.0,51.0,5.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.sec.gov/Archives/edgar/data/113686...,https://www.sec.gov/Archives/edgar/data/113686...,1.278900e+09,NaN,NaN,NaN,NaN,NaN,NaN,2025
9881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.sec.gov/Archives/edgar/data/91576/...,https://www.sec.gov/Archives/edgar/data/91576/...,8.427000e+09,NaN,NaN,NaN,NaN,NaN,NaN,2025
9882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.sec.gov/Archives/edgar/data/746515...,https://www.sec.gov/Archives/edgar/data/746515...,1.060052e+10,NaN,NaN,NaN,NaN,NaN,NaN,2025
9883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.sec.gov/Archives/edgar/data/879101...,https://www.sec.gov/Archives/edgar/data/879101...,1.399361e+09,NaN,NaN,NaN,NaN,NaN,NaN,2025
9884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,https://www.sec.gov/Archives/edgar/data/107075...,https://www.sec.gov/Archives/edgar/data/107075...,5.684000e+09,NaN,NaN,NaN,NaN,NaN,NaN,2025

In [26]:
file_path="C:/Users/ibrah/OneDrive/Masaüstü/ranking.xlsx"

ranked_df.to_excel(file_path, index=False)

In [39]:
import yfinance as yf
import pandas as pd

portfolio_returns = []

for year in range(2000, 2025):
    buy_date = f"{year}-04-01"
    sell_date = f"{year+1}-03-30"
    
    top20 = ranked_df[ranked_df['ranking_year'] == year].nsmallest(20, 'final_rank')
    tickers = top20['symbol'].dropna().unique().tolist()

    if len(tickers) == 0:
        continue

    # Download adjusted close prices
    price_data = yf.download(tickers, start=buy_date, end=sell_date)['Close']

    # Ensure price_data is a DataFrame
    if isinstance(price_data, pd.Series):
        price_data = price_data.to_frame()

    # Forward-fill to handle missing weekends/holidays
    price_data = price_data.ffill().bfill()

    # Convert buy/sell dates to Timestamps and find closest available dates
    buy_date_actual = price_data.index[price_data.index.get_indexer([pd.Timestamp(buy_date)], method='nearest')[0]]
    sell_date_actual = price_data.index[price_data.index.get_indexer([pd.Timestamp(sell_date)], method='nearest')[0]]

    # Extract prices on closest available dates
    buy_prices = price_data.loc[buy_date_actual]
    sell_prices = price_data.loc[sell_date_actual]

    # Calculate returns
    returns = (sell_prices / buy_prices) - 1
    avg_return = returns.mean()

    portfolio_returns.append({
        'year': year,
        'buy_date': str(buy_date_actual.date()),
        'sell_date': str(sell_date_actual.date()),
        'average_return': avg_return,
        'top20_tickers': tickers
    })

# Create final results DataFrame
results_df = pd.DataFrame(portfolio_returns)

[*********************100%***********************]  20 of 20 completed

1 Failed download:
['HCA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2000-04-01 -> 2001-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 954565200, endDate = 985928400")')
[*********************100%***********************]  20 of 20 completed

2 Failed downloads:
['HCA', 'PLL']: YFPricesMissingError('possibly delisted; no price data found  (1d 2001-04-01 -> 2002-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 986101200, endDate = 1017464400")')
[*********************100%***********************]  20 of 20 completed

1 Failed download:
['HCA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2002-04-01 -> 2003-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1017637200, endDate = 1049000400")')
[*********************100%***********************]  20 of 20 completed

1 Failed download:
['HCA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2003-04-01 -> 2004-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1049173200, endDate = 1080622800")')
[*********************100%***********************]  20 of 20 completed

1 Failed download:
['HCA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2004-04-01 -> 2005-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1080795600, endDate = 1112158800")')
[*********************100%***********************]  20 of 20 completed

2 Failed downloads:
['HCA', 'PLL']: YFPricesMissingError('possibly delisted; no price data found  (1d 2005-04-01 -> 2006-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1112331600, endDate = 1143694800")')
[*********************100%***********************]  20 of 20 completed

1 Failed download:
['HCA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2006-04-01 -> 2007-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1143867600, endDate = 1175227200")')
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed

1 Failed download:
['MMI']: YFPricesMissingError('possibly delisted; no price data found  (1d 2012-04-01 -> 2013-03-30) (Yahoo error = "Data doesn\'t exist for startDate = 1333252800, endDate = 1364616000")')
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed
[*********************100%***********************]  20 of 20 completed

In [40]:
results_df

,year,buy_date,sell_date,average_return,top20_tickers
0,2000,2000-04-03,2001-03-29,0.374879,"[GIS, CPB, K, EXC, PEP, CL, HCA, KR, SLM, TROW..."
1,2001,2001-04-02,2002-03-28,0.233820,"[PLL, DLX, CPB, EHC, COP, EOG, KR, K, CL, NYT,..."
2,2002,2002-04-01,2003-03-28,-0.072632,"[YUM, DLX, GIS, HCA, EOG, SLM, K, CL, KR, MO, ..."
3,2003,2003-04-01,2004-03-29,0.421360,"[YUM, DLX, CL, EFX, KR, K, CNP, TROW, HCA, VZ,..."
4,2004,2004-04-01,2005-03-29,0.185571,"[YUM, HCA, CPB, CL, EFX, SPG, K, VZ, EOG, KR, ..."
5,2005,2005-04-01,2006-03-29,0.178355,"[PLL, YUM, HCA, SPG, FNMA, CL, EFX, CPB, PGR, ..."
6,2006,2006-04-03,2007-03-29,0.204547,"[HCA, CL, YUM, FNMA, R, KR, EFX, VZ, K, CPB, A..."
7,2007,2007-04-02,2008-03-28,0.001782,"[YUM, R, CL, KR, DRI, EFX, UPS, K, VZ, XOM, MC..."
8,2008,2008-04-01,2009-03-27,-0.296433,"[R, CLX, CL, EL, RSG, KR, CPB, DRI, VZ, EXC, S..."
9,2009,2009-04-01,2010-03-29,0.527616,"[UPS, R, CL, XOM, K, KR, DRI, CPB, SPG, PEP, E..."
10,2010,2010-04-01,2011-03-29,0.255093,"[R, VZ, YUM, UPS, CL, K, CPB, DRI, MCD, EXC, T..."
11,2011,2011-04-01,2012-03-29,0.148974,"[R, UPS, CLX, CL, VZ, KR, SPG, TPR, CPB, MCD, ..."
12,2012,2012-04-02,2013-03-28,0.175034,"[MMI, R, UPS, CL, TRIP, KR, MCD, TPR, VZ, KMI,..."
13,2013,2013-04-01,2014-03-28,0.060741,"[THC, VZ, CL, KR, AIV, YUM, CPB, KDP, MCD, DRI..."
14,2014,2014-04-01,2015-03-27,0.217838,"[PRU, THC, CL, UPS, YUM, CLX, KR, DLTR, AIV, M..."
15,2015,2015-04-01,2016-03-29,0.062503,"[PRU, VRSK, AIZ, THC, VZ, UPS, CL, YUM, KR, SH..."
16,2016,2016-04-01,2017-03-29,0.178922,"[VZ, UNM, THC, PRU, AIZ, UPS, SHW, SPG, YUM, C..."
17,2017,2017-04-03,2018-03-29,0.124829,"[PRU, UNM, VZ, SPG, WU, INTU, AIZ, HD, KR, CLX..."
18,2018,2018-04-02,2019-03-29,0.177905,"[UNM, PRU, INTU, FE, VZ, HD, SPG, CLX, KDP, AI..."
19,2019,2019-04-01,2020-03-27,-0.149972,"[PRU, SPG, CLX, KR, MO, VZ, AMT, URI, JWN, AIZ..."
20,2020,2020-04-01,2021-03-29,1.149953,"[SPG, AIV, CL, MO, IDXX, CLX, URI, AMT, PEP, J..."
21,2021,2021-04-01,2022-03-29,0.142307,"[HCA, CL, MO, MTD, HD, CHTR, AMT, KR, IRM, SHW..."
22,2022,2022-04-01,2023-03-29,-0.036820,"[CL, CHTR, SPG, IDXX, IRM, MTD, UNP, CLX, AMT,..."
23,2023,2023-04-03,2024-03-28,0.218870,"[PRU, CHTR, APA, SPG, UNP, CL, IRM, MTD, CZR, ..."
24,2024,2024-04-01,2025-03-24,0.146680,"[CHTR, NCLH, VRSK, GDDY, CL, APA, RCL, IRM, AM..."